---
- name: Instalando php-fpm
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-sqlite
    - sqlite3
    - python-mysqldb

- name: Copia config Wordpress
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm
