---
- name: Instalando MySQL
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   - MySQL-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
